### ISSUE TITLE
Error getting SSH address 500 QEMU guest agent is not running

### ISSUE THREAD

**Issue by goffinf** [tylert/packer-build#34] opened 2020-07-06 23:01 UTC
**Packer version:**
```
$ packer version
Packer v1.6.0
```
**Builder: proxmox**

**Proxmox version:**
```
pveversion --verbose
proxmox-ve: 6.2-1 (running kernel: 5.4.44-1-pve)
pve-manager: 6.2-6 (running version: 6.2-6/ee1d7754)
pve-kernel-5.4: 6.2-3
pve-kernel-helper: 6.2-3
pve-kernel-5.4.44-1-pve: 5.4.44-1
pve-kernel-5.4.34-1-pve: 5.4.34-2
...
```

I am trying to run a Packer build using the ubuntu-20.04-live-server-amd64.iso, but when the boot_command runs the build just hangs waiting to get an SSH connection to the launched instance. When the ssh_timeout is reached the build fails and the VM is destroyed.

The Packer log reports that the SSH address cannot be obtained because the QEMU guest agent isn't running.  It wont be on a fresh ISO and I also set the communicator to ssh, and disabled the qemu_agent, so I'm not sure why this is happening ?

```
...
  "builders": [
    {
      ...
      "communicator": "ssh",
...
      "qemu_agent": false,
      "ssh_handshake_attempts": "50",
      "ssh_username": "{{user `ssh_username`}}",
      "ssh_password": "{{user `ssh_password`}}",
      "ssh_pty": true,
      "ssh_timeout": "{{user `ssh_timeout`}}",
```
**packer log:**
![image](https://user-images.githubusercontent.com/2772752/86661013-2fe15780-bfe3-11ea-9943-1c835831f4a6.png)

**build times-out:**
![image](https://user-images.githubusercontent.com/2772752/86662337-8733f780-bfe4-11ea-8eac-066342590a8c.png)

I have copied the complete Packer build file and the user-data below and there is some further detail on this thread which speaks to similar issues (I think I have explored most suggestions here) : https://github.com/hashicorp/packer/issues/9115

Any guidance on how to ensure that the Packer build uses ssh rather than the qemu agent would be much appreciated (or anything else you think might be the culprit).

Kind Regards

Fraser.

**host.json:**
```
{
  "builders": [
    {
      "boot_command": [
        "<enter><wait20><enter><f6><esc><wait>",
        "autoinstall ds=nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/",
        "<enter>"
      ],
      "boot_wait": "{{user `boot_wait`}}",
      "communicator": "ssh",
      "disks": [
        {
          "disk_size": "{{user `home_volume_size`}}",
          "storage_pool": "local-lvm",
          "storage_pool_type": "lvm-thin",
          "type": "scsi",
          "format": "raw"
        }
      ],
      "http_directory": "{{user `http_directory`}}",
      "insecure_skip_tls_verify": true,
      "iso_checksum": "{{user `iso_checksum_type`}}:{{user `iso_checksum`}}",
      "iso_file": "{{user `iso_file`}}",
      "memory": 2048,
      "name": "ubuntu-20-04-base",
      "network_adapters": [
        {
          "bridge": "vmbr0",
          "model": "virtio"
        }
      ],
      "node": "{{user `proxmox_target_node`}}",
      "password": "{{user `proxmox_server_pwd`}}",
      "proxmox_url": "https://{{user `proxmox_server_hostname`}}:{{user `proxmox_server_port`}}/api2/json",
      "qemu_agent": false,
      "ssh_handshake_attempts": "50",
      "ssh_username": "{{user `ssh_username`}}",
      "ssh_password": "{{user `ssh_password`}}",
      "ssh_pty": true,
      "ssh_timeout": "{{user `ssh_timeout`}}",
      "type": "proxmox",
      "unmount_iso": true,
      "username": "{{user `proxmox_server_user`}}"
    }
  ],
  "provisioners": [
    {
      "execute_command": "{{ .Vars }} sudo -E -S sh '{{ .Path }}'",
      "inline": [
        "ls /"
      ],
      "type": "shell"
    }
  ],
  "variables": {
    "boot_wait": "2s",
    "http_directory": "http",
    "iso_checksum": "caf3fd69c77c439f162e2ba6040e9c320c4ff0d69aad1340a514319a9264df9f",
    "iso_checksum_type": "sha256",
    "iso_file": "local:iso/ubuntu-20.04-live-server-amd64.iso",
    "proxmox_server_hostname": "proxmox-002",
    "proxmox_server_port": "8006",
    "proxmox_server_pwd": "xxxxxxxxx",
    "proxmox_server_user": "xxxxxxxx",
    "proxmox_target_node": "home",
    "ssh_handshake_attempts": "20",
    "ssh_password": "ubuntu",
    "ssh_username": "ubuntu",
    "ssh_timeout": "10m"
  }
}

```

**user-data:**
```
#cloud-config
autoinstall:
  identity:
    hostname: ubuntu-20-04-base
    password: '$6$wdAcoXrU039hKYPd$508Qvbe7ObUnxoj15DRCkzC3qO7edjH0VV7BPNRDYK4QR8ofJaEEF2heacn0QgD.f8pO8SNp83XNdWG6tocBM1'
    username: ubuntu
  keyboard:
    layout: en
    #toggle: null
    variant: 'gb'
  late-commands:
    - sed -i 's/^#*\(send dhcp-client-identifier\).*$/\1 = hardware;/' /target/etc/dhcp/dhclient.conf
    - 'sed -i "s/dhcp4: true/&\n      dhcp-identifier: mac/" /target/etc/netplan/00-installer-config.yaml'
  locale: en_GB
  network:
    network:
      version: 2
      ethernets:
        ens33:
          dhcp4: true
          dhcp-identifier: mac
  ssh:
    allow-pw: true
    authorized-keys:
    - "ssh-rsa AAAAB3NzaC1yc2..."
    install-server: true
  version: 1
```

**Comment by tylert** [comment] 2020-07-07 00:36
Hmm... This is the first I've heard of a "qemu agent".  Clearly, I have another item to add to my reading TODO list.  I would have thought using Packer's "ssh communicator" would have been sufficient.

I also haven't yet used proxmox or done any tests with it.  Perhaps the proxmox builder is the difference.  Are you able to perform a similar build using the `qemu` builder on another Linux baremetal machine?  That's one of the reasons why I like to retain support for 2 different builders in my templates to try to give me a second path to rule out differences that might be caused by the different type-2 hypervisors.

You'll note that my current templates make use of the `ubuntu-20.04-legacy-server.iso` + preseed rather than the newer "live-server" + cloud-init as in your example template.  I know about it but haven't had time yet to fix my own template yet (pull-requests welcome).

Other places you might also want to look include:
* https://github.com/geerlingguy/packer-boxes/blob/master/ubuntu2004/box-config.json
* https://nickcharlton.net/posts/automating-ubuntu-2004-installs-with-packer.html
* https://beryju.org/blog/automating-ubuntu-server-20-04-with-packer

If you're not having much luck with those, there's also the Boxcutter project at https://github.com/boxcutter/ubuntu which might also offer you some additional inspiration.

Hope this gives you a few more ideas of what to try next.  Good luck.

**Comment by tylert** [comment] 2020-07-07 00:39
Since this particular issue isn't an issue with these `packer_build` templates, I'd like to close this issue as it doesn't really belong here.

**Closed by tylert** 2020-07-07 00:39 UTC

**Comment by goffinf** [comment] 2020-07-07 09:36
@tylert (Tyler),

thanks for your response and helpful suggestions. So sorry I got my wires crossed, I was intending to raise an issue in the github repo for the maintainer of the packer proxmox builder and accidentally put it here instead (you were one of the many leads I was following). Nonetheless, it is always good for those with common interests to 'touch base' so hopefully you may get something from this short discourse also.

Happy for the issue to be closed here.

Kind Regards

Fraser.
